### ISSUE TITLE
Bootlooping on Arrow OS Pie

### ISSUE THREAD

**Issue by sharukhmohammed** [Magisk-Modules-Repo/lawnstep#1]
This is causing a bootloop for ArrowOS Pie ROM for potter.
Currently using this https://forum.xda-developers.com/g5-plus/development/rom-pie-9-x-arrowos-9-x-t3838052

**Comment by skittles9823** [comment]
Bootlooping on install, or uninstall?

**Comment by sharukhmohammed** [comment]
Steps I performed (Twice)

- Installed Lawnchair
- Installed Module from Magisk Repo
- Rebooted
- Now my nav bar changed to classic back home recent (including recent screen) like oreo
- I went back to magisk and uninstalled
- Rebooted
- In Bootloop, nothing could save device, instead of wiping system and data

**Comment by skittles9823** [comment]
Okay yea. To uninstall you need to flash the module again.

**Comment by sharukhmohammed** [comment]
Mentioning this in the readme would be a lot helpful

**Comment by karthikmuralidharan** [comment]
Faced the same issue on Oneplus 6 with OOS 9.0.2 rooted with magisk.

**Comment by skittles9823** [comment]
Read the previous comments. Flash the module to uninstall it.

**Comment by sharukhmohammed** [comment]
So, instead of fixing the issue, uninstalling and not using the module is the solution?

**Comment by skittles9823** [comment]
No, you need to flash it to uninstall to make sure the uninstaller script runs. Uninstalling via the bin icon in magisk manager is the reason you boot loop.
